# Generated by Django 3.1.7 on 2021-04-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='Слово')),
                ('score', models.IntegerField(verbose_name='Оценка сложности')),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Оценка сложности')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('symbol', models.IntegerField(blank=True, null=True, verbose_name='Кол-во символов')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
            },
        ),
    ]
