# Generated by Django 3.1.7 on 2021-02-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210224_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка сложности'),
        ),
        migrations.AlterField(
            model_name='texts',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
