# Generated by Django 3.1.7 on 2021-03-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210224_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, verbose_name='Слово')),
                ('score', models.IntegerField(verbose_name='Оценка сложности')),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.AddField(
            model_name='texts',
            name='slug',
            field=models.SlugField(default=123, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
