# Generated by Django 3.1.7 on 2021-04-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210411_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='symbol',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во символов'),
        ),
    ]
